name: ReportPE
version: 1.0.0
author: applqpak
api: [1.0.0]
main: ReportPE\Main
commands:
  report:
    description: Báo cáo người chơi!
    usage: "/rpt <ten nguoi choi> <li do>"
    aliases: [rpt, baocao]
    permission: reportpe.command.report
  reports:
    description: Check User Reports!
    usage: "/reports"
    aliases: [rpts]
    permission: reportpe.command.reports
permissions:
  reportpe.command.report:
    default: true
  reportpe.command.reports:
    default: op
